Date:
  name: Date
  in: header
  schema:
    type: string
    pattern: "^[A-Z][a-z]{2}, [0-9]{2} [A-Z][a-z]{2} [0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2} [A-Z]{3}$"
  required: true
  description: Current time and date of request in HTTP Date Header format (RFC 7321)
  example: "Tue, 06 Jul 2016 04:39:43 GMT"

ContentMd5:
  name: Content-MD5
  in: header
  schema:
    type: string
    format: byte
  required: true
  description: Base-64 encoded MD5 hash of request body (without HTTP verb and Headers)
  example: 1B2M2Y8AsgTpgAmY7PhCfg==

Authorization:
  name: Authorization
  in: header
  schema:
    type: string
  required: true
  description: >-
    Header containing HMAC type, organization credentials and request signature
    (more information available at the top of this page)
  example: APIAuth-HMAC-SHA256 112233:oDUPWnSduVE+DmkqQC7m3CP66ycVhQImHxmdW2COmio=
