# Rubocop docs: http://rubocop.readthedocs.io/en/latest/

inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - kitchen/cookbooks/**/*
    - kitchen/tmp/**/*
    - vendor/**
    - package/**

Rails:
  Enabled: false

FileName:
  Exclude:
    - SUSEConnect
    - suse-connect.gemspec
    - Guardfile

RSpec/NestedGroups:
  Max: 4
