openapi: 3.0.0
info:
  title: OEM Partner API
  description: API for creating and listing OEM Partners orders
  version: 1

servers:
  - url: "{protocol}://scc.suse.com/api/oem"
    description: Main (production)
    variables:
      protocol:
        enum:
          - https
        default: https
    basePath: /api/oem

tags:
  - name: partner_orders
    description: API for creating and listing OEM Partners orders

paths:
  /partner_orders:
    get:
      tags:
        - partner_orders
      summary: Get all OEM partner orders.
      parameters:
        - $ref: '#/components/parameters/date'
        - $ref: '#/components/parameters/contentMd5'
        - $ref: '#/components/parameters/authorization'
      responses:
        '200':
          description: A list of all OEM partner orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartnerOrder'
    post:
      tags:
        - partner_orders
      parameters:
        - $ref: '#/components/parameters/date'
        - $ref: '#/components/parameters/contentMd5'
        - $ref: '#/components/parameters/authorization'
      summary: Place an OEM partner order
      requestBody:
        description: Partner order object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartnerOrderObject'
      responses:
        '200':
          description: Partner order created successfully.
          content:
            application/json:
              schema:
                $ref: '#components/schemas/PartnerOrder'

components:
  schemas:
    PartnerOrderObject:
      type: object
      properties:
        partner_order:
          type: object
          required: true
          properties:
            oem_token:
              type: string
              required: true
              example: 987654
            purchased_at:
              type: string
              format: date-time
              required: true
              example: "2016-07-06T08:48:22.000Z"
            email:
              type: string
              format: email
              example: john.doe@example.com
            partner_order_items:
              type: array
              items:
                $ref: '#/components/schemas/PartnerOrderItemRequest'
              required: true
    PartnerOrderItemRequest:
      type: object
      properties:
        sku:
          type: string
          required: true
          example: 345-67890
        system_limit:
          type: integer
          format: int32
          minimum: 0
          required: true
          example: 2
    PartnerOrder:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        purchased_at:
          type: string
          format: date-time
          example: "2016-07-06T08:48:22.000Z"
        created_at:
          type: string
          format: date-time
          example: "2016-07-06T08:59:29.568Z"
        oem_token:
          type: string
          example: "987654"
        email:
          oneOf:
            - type: string
              format: email
              example: john.doe@example.com
            - type: null
              example: null
        partner_order_items:
          type: array
          items:
            $ref: '#/components/schemas/PartnerOrderItem'
          exmaple:
            - id: 2
              system_limit: 4
              sku: 234-56789
    PartnerOrderItem:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        system_limit:
          type: integer
          format: int32
          example: 2
        sku:
          type: string
          example: 345-67890
  parameters:
    date:
      name: Date
      in: header
      schema:
        type: string
        pattern: "^[A-Z][a-z]{2}, [0-9]{2} [A-Z][a-z]{2} [0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2} [A-Z]{3}$"
      required: true
      description: Current time and date of request in HTTP Date Header format (RFC 7321)
      example: "Tue, 06 Jul 2016 04:39:43 GMT"
    contentMd5:
      name: Content-MD5
      in: header
      schema:
        type: string
        format: byte
      required: true
      description: Base-64 encoded MD5 hash of request body (without HTTP verb and Headers)
      example: 1B2M2Y8AsgTpgAmY7PhCfg==
    authorization:
      name: Authorization
      in: header
      schema:
        type: string
      required: true
      description: Header containing HMAC type, organization credentials and request signature
      example: APIAuth-HMAC-SHA256 112233:oDUPWnSduVE+DmkqQC7m3CP66ycVhQImHxmdW2COmio=
